[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }
svelte = { command = "svelteserver" }
wakatime = { command = "wakatime-ls" }

[[language]]
name = "mdx"
scope = "source.mdx"
injection-regex = "^(mdx)$"
file-types = ["mdx"]
roots = [".marksman.toml"]
indent = { tab-width = 2, unit = "  " }
language-servers = [
  { name = "marksman"},
  { name = "wakatime"},
]

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "wakatime" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "wakatime" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "wakatime" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "wakatime" ]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome", "wakatime" ]

[[language]]
name = "svelte"
language-servers = [ { name = "svelte" }, "wakatime" ]

[[language]]
name = "go"
language-servers = [ "gopls", "wakatime" ]

[[language]]
name = "gomod"
language-servers = [ "gopls", "wakatime" ]

[[language]]
name = "gowork"
language-servers = [ "gopls", "wakatime" ]

[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "wakatime" ]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "wakatime" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "wakatime" ]

[[language]]
name = "protobuf"
language-servers = [ "bufls", "wakatime" ]

[[language]]
name = "python"
language-servers = [ "pylsp", "wakatime" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "wakatime" ]

[[language]]
name = "toml"
language-servers = [ "taplo", "wakatime" ]

[[language]]
name = "yaml"
language-servers = [ "yaml-language-server", "wakatime" ]

[[language]]
name = "nix"
language-servers = [ "nil", "wakatime" ]

[[language]]
name = "bash"
language-servers = [ "bash-language-server", "wakatime" ]

[[language]]
name = "fish"
language-servers = [ "wakatime" ]

