[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }
svelte = { command = "svelteserver" }
wakatime = { command = "wakatime-ls" }

[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]

[language-server.vtsls.config.typescript.preferences]
importModuleSpecifier = "non-relative"

[language-server.vtsls.config.javascript.preferences]
importModuleSpecifier = "non-relative"

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
experimental = { useFlatConfig = true }
problems = { shortenToSingleLine = false }
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }

[language-server.eslint.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = false }

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[[language]]
name = "mdx"
scope = "source.mdx"
injection-regex = "^(mdx)$"
file-types = ["mdx"]
roots = [".marksman.toml"]
indent = { tab-width = 2, unit = "  " }
language-servers = [
  { name = "marksman"},
  { name = "wakatime"},
]

[[language]]
name = "javascript"
language-servers = [ { name = "vtsls", except-features = [ "format" ] }, "eslint", "biome", "wakatime" ]
formatter = { command = "npx", args = ["prettier", "--stdin-filepath", "file.js"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "vtsls", except-features = [ "format" ] }, "eslint", "biome", "wakatime" ]
formatter = { command = "npx", args = ["prettier", "--stdin-filepath", "file.ts"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ { name = "vtsls", except-features = [ "format" ] }, "eslint", "biome", "wakatime" ]
formatter = { command = "npx", args = ["prettier", "--stdin-filepath", "file.tsx"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ { name = "vtsls", except-features = [ "format" ] }, "eslint", "biome", "wakatime" ]
formatter = { command = "npx", args = ["prettier", "--stdin-filepath", "file.jsx"] }
auto-format = true

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome", "wakatime" ]

[[language]]
name = "svelte"
language-servers = [ { name = "svelte" }, "wakatime" ]

[[language]]
name = "go"
language-servers = [ "gopls", "golangci-lint-lsp", "wakatime" ]
formatter = { command = "gofmt" }

[[language]]
name = "gomod"
language-servers = [ "gopls", "wakatime" ]

[[language]]
name = "gowork"
language-servers = [ "gopls", "wakatime" ]

[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "wakatime" ]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "wakatime" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "wakatime" ]

[[language]]
name = "protobuf"
language-servers = [ "bufls", "wakatime" ]

[[language]]
name = "python"
language-servers = [ "pylsp", "wakatime" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "wakatime" ]

[[language]]
name = "toml"
language-servers = [ "taplo", "wakatime" ]

[[language]]
name = "yaml"
language-servers = [ "yaml-language-server", "wakatime" ]

[[language]]
name = "nix"
language-servers = [ "nil", "wakatime" ]

[[language]]
name = "bash"
language-servers = [ "bash-language-server", "wakatime" ]

[[language]]
name = "fish"
language-servers = [ "wakatime" ]

